name: Deploy Client

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Install Rollup Linux Binary
        run: npm install --no-save @rollup/rollup-linux-x64-gnu@4.57.1
      - name: Build rules
        run: npm run build -w packages/rules
      - name: Build client
        env:
          VITE_BASE: /${{ github.event.repository.name }}/
          VITE_SERVER_URL: wss://arrogant-leeanne-strategamma-82d356d8.koyeb.app
        run: npm run build -w apps/client
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/client/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
